version: "3"
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    ports:
      - "5432:5432"
    volumes:
      - postgres_db:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        - RAILS_ENV=${RAILS_ENV}
        - SECRET_KEY_BASE=${SECRET_KEY_BASE}
    environment:
      - RAILS_ENV=${RAILS_ENV}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
    command: sh -c "rm -f tmp/pids/server.pid && rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
      - bundle_data:/usr/local/bundle/gems
    ports:
      - "3000:3000"
    depends_on:
      - db
    tty: true
    stdin_open: true
  redis:
    image: redis:6.2.6
    command: redis-server
    volumes:
      - redis_data:/data

volumes:
  postgres_db:
  bundle_data:
  redis_data:
