version: "3"
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    ports:
      - "5432:5432"
    volumes:
      - postgres_db:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: sh -c "rm -f tmp/pids/server.pid && rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
      - bundle_data:/usr/local/bundle/gems
    ports:
      - "3000:3000"
    depends_on:
      - db
      - mailcatcher
      - redis
    tty: true
    stdin_open: true
  mailcatcher:
    restart: on-failure:10
    image: dockage/mailcatcher:0.7.1
    ports:
      - "1080:1080"
      - "1025:1025"
  redis:
    image: redis:7.0
    ports:
      - "6379:6379"
volumes:
  postgres_db:
  bundle_data:
  redis_data:
