---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/test":
    get:
      summary: check api
      tags:
      - Test Check
      responses:
        '200':
          description: Server is healthy
          content:
            application/json:
              schema:
                type: object
            application/xml:
              schema:
                type: object
servers:
- url: "{defaultHost}"
  variables:
    defaultHost:
      default: http://localhost:3000
